apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25102106
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25102106:2c0c523343f885753cff3b0cb7d23d1ca5ae7b43@sha256:27fbe52af65c634fb8ba48bd8ab3f83123677f61624012ab8f82d49308358350 # use pre-built to bootstrap
          name: app-inference
